apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: dev
spec:
  selector:
    app: kafka
  ports:
    - name: advertise
      port: 9092
    - name: client
      port: 29092
  clusterIP: None

# vim: et sw=2 ts=2 sts=2 :
