apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: dev
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:latest
          name: zookeeper
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: broker-configmap
                  key: zookeeper_client_port
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: broker-configmap
                  key: zookeeper_tick_time
          ports:
            - containerPort: 2181
              name: zookeeper

# vim: et sw=2 ts=2 sts=2 :
