kind: Service
apiVersion: v1
metadata:
  name: yerbamate-payment-svc
  namespace: dev
spec:
  selector:
    app: yerbamate-payment
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

# vim: et sw=2 ts=2 sts=2 :
