apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: yerbamate-checkout-hpas
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: yerbamate-checkout
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 95
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 125

# vim: et sw=2 ts=2 sts=2 :
